# Generated by Django 4.2.5 on 2023-11-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('E_mail', models.EmailField(blank=True, max_length=20, null=True)),
                ('A_dress', models.TextField(blank=True, max_length=100, null=True)),
                ('C_ity', models.CharField(blank=True, max_length=20, null=True)),
                ('Country', models.CharField(blank=True, max_length=20, null=True)),
                ('Zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('Tele', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
