# Generated by Django 4.2.5 on 2023-09-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListRestDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rest_list', models.CharField(blank=True, max_length=100, null=True)),
                ('Rest_type', models.CharField(blank=True, max_length=100, null=True)),
                ('Branches', models.CharField(blank=True, max_length=100, null=True)),
                ('Res_img', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
