# Generated by Django 4.2.5 on 2023-09-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantapp', '0002_listrestdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='listrestdb',
            name='Review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
