# Generated by Django 4.2.5 on 2023-09-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantapp', '0003_listrestdb_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listrestdb',
            name='Res_img',
            field=models.ImageField(blank=True, null=True, upload_to='Image'),
        ),
    ]
