# Generated by Django 4.2.5 on 2023-10-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantapp', '0004_alter_listrestdb_res_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='listrestdb',
            name='Cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
